<aside id="markuphelp"><h2>Markup Help</h2><pre>
# Section heading

## Subsection

Formatting:  *italics*, **bold**, super^script^, sub~script~, ~~strikeout~~.

A line break can be forced with two spaces at the end of the line.

> Indented quotation

Links:
[external](http://google.com),
[Wiki Link](),
![image](/img/icons/folder.png),
[to heading](#section-heading).

Indented code block:

    #include <stdbool.h>

Delimited code block:

~~~ { .haskell }
let a = 1:a in head a
~~~

- bulleted
- list

* * * * *

1.  ordered
2.  list
    a. sublist (indent 4 spaces)
    b. another
3.  item three

term
:   definition
orange
:   orange fruit
</pre>
</aside>
