  <ul
    ><li$if(isdiscusspage)$$else$ class="selected"$endif$><a href="$base$$articleUrl$" class="article">Article ↓</a
      ><ul
        ><li><a href="$base$$articleUrl$">Read</a></li
        ><li><a href="$base$/_showraw$articleUrl$">Source code</a></li
        ><li class="hr"><hr/></li
        ><li><a href="$base$/_edit$articleUrl$">Edit</a></li
        ><li><a href="$base$/_delete$articleUrl$">Delete</a></li
        ><li class="hr"><hr/></li
        ><li><a href="$base$/_history$articleUrl$">History</a></li
        ><li><a href="$base$/_feed$articleUrl$" class="feed">Atom feed</a></li
        ><li class="hr"><hr/></li
        ><li><a href="$base$$articleUrl$?printable$if(revision)$&amp;revision=$revision$$endif$">Print version</a></li
        ><li><a>Export as →</a>
          <ul
            ><li><a href="$base$$articleUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=PDF">PDF</a></li
            ><li><a href="$base$$articleUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=LaTeX">LaTeX</a></li
            ><li><a href="$base$$articleUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=ConTeXt">ConTeXt</a></li
            ><li><a href="$base$$articleUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=Texinfo">Texinfo</a></li
            ><li><a href="$base$$articleUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=reST">reST</a></li
            ><li><a href="$base$$articleUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=markdown">markdown</a></li
            ><li><a href="$base$$articleUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=plain+text">plain text</a></li
            ><li><a href="$base$$articleUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=MediaWiki">MediaWiki</a></li
            ><li><a href="$base$$articleUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=man">man</a></li
            ><li><a href="$base$$articleUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=DocBook">DocBook</a></li
            ><li><a href="$base$$articleUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=Slidy">Slidy</a></li
            ><li><a href="$base$$articleUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=S5">S5</a></li
            ><li><a href="$base$$articleUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=ODT">ODT</a></li
            ><li><a href="$base$$articleUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=EPUB">EPUB</a></li
            ><li><a href="$base$$articleUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=Org">Org</a></li
            ><li><a href="$base$$articleUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=Textile">Textile</a></li
            ><li><a href="$base$$articleUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=RTF">RTF</a></li
          ></ul
        ></li
      ></ul
    ></li
    ><li$if(isdiscusspage)$ class="selected"$else$$endif$><a href="$base$$discussionUrl$" class="discussion">Discussion ↓</a
      ><ul
        ><li><a href="$base$$discussionUrl$">Read</a></li
        ><li><a href="$base$/_showraw$discussionUrl$">Source code</a></li
        ><li class="hr"><hr/></li
        ><li><a href="$base$/_edit$discussionUrl$">Edit</a></li
        ><li><a href="$base$/_delete$discussionUrl$">Delete</a></li
        ><li class="hr"><hr/></li
        ><li><a href="$base$/_history$discussionUrl$">History</a></li
        ><li><a href="$base$/_feed$discussionUrl$" class="feed">Atom feed</a></li
        ><li class="hr"><hr/></li
        ><li><a href="$base$$discussionUrl$?printable$if(revision)$&amp;revision=$revision$$endif$">Print version</a></li
        ><li><a>Export as →</a>
          <ul
            ><li><a href="$base$$discussionUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=PDF">PDF</a></li
            ><li><a href="$base$$discussionUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=LaTeX">LaTeX</a></li
            ><li><a href="$base$$discussionUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=ConTeXt">ConTeXt</a></li
            ><li><a href="$base$$discussionUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=Texinfo">Texinfo</a></li
            ><li><a href="$base$$discussionUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=reST">reST</a></li
            ><li><a href="$base$$discussionUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=markdown">markdown</a></li
            ><li><a href="$base$$discussionUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=plain+text">plain text</a></li
            ><li><a href="$base$$discussionUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=MediaWiki">MediaWiki</a></li
            ><li><a href="$base$$discussionUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=man">man</a></li
            ><li><a href="$base$$discussionUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=DocBook">DocBook</a></li
            ><li><a href="$base$$discussionUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=Slidy">Slidy</a></li
            ><li><a href="$base$$discussionUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=S5">S5</a></li
            ><li><a href="$base$$discussionUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=ODT">ODT</a></li
            ><li><a href="$base$$discussionUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=EPUB">EPUB</a></li
            ><li><a href="$base$$discussionUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=Org">Org</a></li
            ><li><a href="$base$$discussionUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=Textile">Textile</a></li
            ><li><a href="$base$$discussionUrl$?export$if(revision)$&amp;revision=$revision$$endif$&amp;format=RTF">RTF</a></li
          ></ul
        ></li
      ></ul
    ></li
  ></ul>
